build:
  artifacts:
    paths:
      - build/libs/*.jar
  image: "gradle:5.0-jdk8-alpine"
  script:
    - "gradle build"
  stage: build
deploy_staging:
  environment:
    name: staging
    url: "https://mathflake.com"
  only:
    - develop
  script:
    - "apk upgrade && apk update"
    - "apk add openssh-client"
    - "apk add sshpass"
    - "sshpass -p \"$STAGING_SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com"
    - "sshpass -p \"$STAGING_SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker pull registry.gitlab.com/mathflake/api"
    - "sshpass -p \"$STAGING_SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER \"docker container stop mathflake_api && docker container rm mathflake_api || true\""
    - "sshpass -p \"$STAGING_SERVER_PASSWORD\" ssh -o StrictHostKeyChecking=no $STAGING_SERVER_USER@$STAGING_SERVER docker run --name mathflake_api -p 80:80 -d registry.gitlab.com/mathflake/api"
  stage: deploy
image: "docker:latest"
