image: maven:3-jdk-11

stages:
    - build
    - test
    - deploy
    - monitor



#################################################
#build

# build the backend
build_backend:
  script: 
    - cd backend 
    - mvn -Dmaven.test.skip clean package
  stage: build
  tags: 
    - analytics
# build the frontend
build_frontend:
  image: node:10
  script:
    - cd frontend
    - npm i
    - npm run build
  stage: build
  tags:
    - analytics
############################################################
#test

# Test stage jobs


test_backend:
  stage: test
  tags:
    - analytics
  services:
    - mongo
  script:
    - cd backend
    - mvn test
      -Dspring.data.mongodb.uri="mongodb://mongo:27017/"
  dependencies:
    - build_backend
#######################################################
# deploy
deploy_app:
  image: tmaier/docker-compose:latest
  image: maven:3-jdk-11

  services:
    - docker:dind

  before_script:
    - cd backend
    - docker info
    - docker-compose --version
  stage: deploy
  tags:
    - analytics
  script:
    - mvn install package
    - docker-compose build
  dependencies:
    - build_backend

    
##################################################


# monitor
sonar_check:
  image: maven:3-jdk-11
  stage : monitor
  services:
    - mongo

  tags :
    - analytics
  # only : ["master"]
  script :
    - cd backend
    - mvn --batch-mode verify sonar:sonar
      -Dspring.data.mongodb.uri="mongodb://mongo:27017/"
      -Dsonar.host.url="http://rio.inf.usi.ch:9000/"
      -Dsonar.login="group4"
      -Dsonar.password="group4"
      -Dsonar.analysis.mode=publish
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

