image: ubuntu:16.04

stages:
    - build
    - test
    - deploy
    - monitor



#################################################
#build

# build the backend
build_backend:
  script:
    - apt-get update
    - apt-get -y install sudo
    - apt-get -y install git
    - apt-get -y install curl
    - apt-get -y install libcurl3
    - apt-get -y install libarchive13
    - apt-get -y install maven
    - apt-get -y install openjdk-8-jdk
    - curl http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu16.04.deb --output srcml_1.0.0-1_ubuntu16.04.deb
    - dpkg -i srcml_1.0.0-1_ubuntu16.04.deb
    - cd backend
    - mvn -Dmaven.test.skip clean package
    - rm jar_file/group4-software-analytics-0.0.1-SNAPSHOT.jar
    - cp target/group4-software-analytics-0.0.1-SNAPSHOT.jar jar_file
  stage: build
  tags:
    - analytics
# build the frontend
build_frontend:
  image: node:10
  script:
    - cd frontend
    - npm i
    - npm run build
  stage: build
  tags:
    - analytics


########################################################
## deploy
#deploy_app:first:
#  stage: deploy
#  tags:
#    - analytics
#  script:
#    - cd backend
#    - mvn -Dmaven.test.skip clean package
#    - cp target/group4-software-analytics-0.0.1-SNAPSHOT.jar src
#
#
deploy_app:
  image: tmaier/docker-compose:latest
  services:
    - docker:dind
  stage: deploy
  tags:
    - analytics
  script:
    - cd backend
    - docker-compose build
#  dependencies:
#    - build_backend

    
##################################################


# monitor
sonar_check:
  stage : monitor
  services:
    - mongo

  tags :
    - analytics
  # only : ["master"]
  script :
    - apt-get update
    - apt-get -y install sudo
    - apt-get -y install git
    - apt-get -y install curl
    - apt-get -y install libcurl3
    - apt-get -y install libarchive13
    - apt-get -y install maven
    - apt-get -y install openjdk-8-jdk
    - curl http://131.123.42.38/lmcrs/v1.0.0/srcml_1.0.0-1_ubuntu16.04.deb --output srcml_1.0.0-1_ubuntu16.04.deb
    - dpkg -i srcml_1.0.0-1_ubuntu16.04.deb
    - cd backend
    - mvn -Dmaven.test.skip clean package
    - mvn --batch-mode verify sonar:sonar
      -Dspring.data.mongodb.uri="mongodb://mongo:27017/"
      -Dsonar.host.url="http://rio.inf.usi.ch:9000/"
      -Dsonar.login="group4"
      -Dsonar.password="group4"
      -Dsonar.analysis.mode=publish
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

