image: maven:3-jdk-12

variables:

services:
    - docker:dind

stages:
    - build
    - test
    - deploy
    - monitor



#################################################

# build the backend
build_backend: 
  image: "maven:3-jdk-14"
  script: 
    - cd backend 
    - mvn -Dmaven.test.skip clean package
  stage: build
  tags: 
    - analytics
############################################################


# Test stage jobs


test_backend:
  image: "maven:3-jdk-14"
  stage: test
  tags:
    - analytics
  script:
    - cd backend
    - mvn test
#######################################################

# deploy the frontend


build_frontend:
  image: node:10
  script:
    - cd frontend
    - npm i
    - npm run build
  stage: deploy
  tags:
    - analytics
    
    
##################################################


# monitor
sonar_check:
  image: maven:3-jdk-11
  stage : monitor
  services:
    - mongo

  tags :
    - analytics
  # only : ["master"]
  script :
    - cd backend
    - mvn --batch-mode verify sonar:sonar
      -Dspring.data.mongodb.uri="mongodb://mongo:27017/"
      -Dsonar.host.url="http://rio.inf.usi.ch:9000/"
      -Dsonar.login="group4"
      -Dsonar.password="group4"
      -Dsonar.analysis.mode=publish
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID

