version: "3.1"
 
services:
  myapi:
    build: .
    restart: always
    ports: 
      - "80:8080"
    depends_on:
      - db
 
  db:
    image: mongo
    ports:
      - "27017:27017"
    restart: always